version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      # Verify AWS CLI
      - echo "Verifying AWS CLI installation..."
      - aws --version

      # Print cache directory before deletion (for debugging)
      - echo "Cache directory before deletion:"
      - ls -la ~/.aws/cli/cache || echo "No cache folder found"

      # Delete the AWS CLI cache folder
      - rm -rf ~/.aws/cli/cache

      # Install kubectl
      - echo "Installing kubectl..."
      - curl -LO https://dl.k8s.io/release/v1.27.2/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl
      - export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
      - source ~/.bashrc
      - echo "Checking kubectl version..."
      - kubectl version --short --client

      # # Install dependencies
      - echo "Installing dependencies..."
      - yum groupinstall -y "Development Tools"
      # - sudo yum install -y python3-devel cairo cairo-devel cairo-gobject gobject-introspection-devel libffi-devel
      # - yum install -y meson ninja-build
      # - yum install -y cmake

  pre_build:
    commands:
      # Export AWS credentials
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

      - export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig

      # Login to ECR Registry for docker to push the image to ECR Repository
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com
      # - aws eks update-kubeconfig --region ap-northeast-2 --name iteamoa --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/codebuild-iteamoa-loginpage-service-role 

  build:
    commands:
      # Set up image repository details
      - IMAGE_REPO_NAME=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/login
      - IMAGE_TAG=latest

      # Install Python dependencies
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      # - pip install cffi==1.17.1
      # - pip install charset-normalizer==3.3.2
      # - pip install cryptography==43.0.3
      # - pip install cytoolz==0.12.2
      # - pip install decorator==5.1.1
      # - pip install Django==5.1.2
      # - pip install django-cors-headers==4.6.0
      # - pip install executing==2.0.1
      # - pip install fastjsonschema==2.19.0
      # - pip install findspark==2.0.1
      # - pip install frozenlist==1.4.0
      # - pip install hexbytes==0.3.1
      # - pip install idna==3.6
      # - pip install import-ipynb==0.1.4
      # - pip install pip-install==1.3.5
      # - pip install ipython==8.18.1
      # - pip install jedi==0.19.1
      # - pip install jmespath==1.0.1
      # - pip install joblib==1.3.2
      # - pip install jsonschema==4.20.0
      # - pip install jsonschema-specifications==2023.11.1
      # - pip install lru-dict==1.2.0
      # - pip install matplotlib-inline==0.1.6
      # - pip install multidict==6.0.4
      # - pip install nbformat==5.9.2
      # - pip install numpy==1.26.2
      # - pip install pandas==2.1.3
      # - pip install parsimonious==0.9.0
      # - pip install parso==0.8.3
      # - pip install pexpect==4.9.0
      # - pip install platformdirs==4.1.0
      # - pip install prompt-toolkit==3.0.41
      # - pip install protobuf==4.25.1
      # - pip install ptyprocess==0.7.0
      # - pip install pure-eval==0.2.2
      # - pip install py4j==0.10.9.7
      # - pip install pycparser==2.22
      # - pip install pycryptodome==3.19.0
      # - pip install Pygments==2.17.2
      # - pip install python-dateutil==2.9.0.post0
      # - pip install python-dotenv==0.21.0
      # - pip install python-slugify==8.0.1
      # - pip install pytz==2023.3.post1
      # - pip install pyunormalize==15.1.0
      # - pip install referencing==0.31.0
      # - pip install regex==2023.10.3
      # - pip install requests==2.31.0
      # - pip install rlp==3.0.0
      # - pip install rpds-py==0.13.1
      # - pip install s3transfer==0.10.3
      # - pip install scikit-learn==1.3.2
      # - pip install scipy==1.11.4
      # - pip install six==1.16.0
      # - pip install sqlparse==0.5.1
      # - pip install stack-data==0.6.3
      # - pip install text-unidecode==1.3
      # - pip install threadpoolctl==3.2.0
      # - pip install toolz==0.12.0
      # - pip install tqdm==4.66.1
      # - pip install traitlets==5.14.0
      # - pip install typing_extensions==4.8.0
      # - pip install tzdata==2023.3
      # - pip install urllib3==2.2.3
      # - pip install wcwidth==0.2.12
      # - pip install webencodings==0.5.1
      # - pip install websockets==12.0
      # - pip install yarl==1.9.3

      # Collect static files
      - echo "Collecting static files..."
      - python manage.py

      # Migrate database
      - echo "Applying database migrations..."
      - python manage.py migrate
      
      # Build Docker Image
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "Listing Docker images to verify the built image:"
      - docker images
      - echo "Searching for our specific image:"
      - docker images | grep $IMAGE_REPO_NAME
      
  post_build:
    commands:
      # # Push Docker Image to ECR Repository
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG

      # # # Setup kubectl with our EKS Cluster
      # - echo "Setting up kubectl for EKS Cluster iteamoa..."
      # - aws eks update-kubeconfig --name iteamoa --region ap-northeast-2

      # # Export AWS credentials to environment variables
      # - export KUBECONFIG=/root/.kube/config
      

      # # Deploy the latest image to the EKS cluster using Kubernetes manifests
      # - echo "Applying deployment and service files to the cluster..."
      # - kubectl apply -f k8s/login-service-deployment.yaml -n loginpage-namespace
      # - kubectl apply -f k8s/login-service.yaml -n loginpage-namespace

      # # Optionally, confirm that the deployment was successful
      # - echo "Deployment applied. Verifying pods..."
      # - kubectl get pods -n loginpage-namespace