apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codebuild-admin-binding
subjects:
- kind: User
  name: "arn:aws:iam::970547342771:role/codebuild-iteamoa-loginpage-service-role"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
