apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: login-namespace #loginpage-namespace
spec:
  selector:
    app: fargate #loginpage
  ports:
    - protocol: TCP
      port: 80              # LoadBalancer listens on port 8080 for loginpage
      targetPort: 8000
  type: ClusterIP
