apiVersion: v1
kind: Service
metadata:
  name: loginpage-service
  namespace: loginpage-namespace
spec:
  selector:
    app: loginpage
  ports:
    - protocol: TCP
      port: 8081              # LoadBalancer listens on port 8081 for loginpage
      targetPort: 8080        # Forwards to 8080 on the container
  type: ClusterIP
