# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: login-service-deployment
#   namespace: login-namespace 
#   labels:
#     app: fargate
#     svc: login
# spec:
#   replicas: 1  # pods running the service
#   selector:
#     matchLabels:
#       app: fargate
#       svc: login
#   template:
#     metadata:
#      labels:
#       app: fargate
#       svc: login
#     spec:
#       serviceAccountName: login-service-sa  # Attach the IAM role via IRSA
#       containers:
#       - name: login-service
#         image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/login:latest #login-page-local-1:latest #ghcr.io/brynnpark/login-test:latest # Use ECR
#         ports:
#         - containerPort: 8000  # Check container's exposed port 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
  namespace: login-namespace
  labels:
    svc: login
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: login
  template:
    metadata:
      labels:
        svc: login
    spec:
      containers:
        - name: login-service
          image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/login:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ecr-registry-secret  # Secret to authenticate with ECR
