apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: login-local-namespace #loginpage-namespace
spec:
  selector:
    app: local #loginpage
  ports:
    - protocol: TCP
      port: 8080              # LoadBalancer listens on port 8081 for loginpage
      nodePort: 30081
  type: NodePort
