apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
  namespace: login-local-namespace #loginpage-namespace
  labels:
    app: local #fargate
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: local
  template:
    metadata:
     labels:
      app: local
    spec:
      containers:
      - name: loginpage-service
        image: ghcr.io/brynnpark/login-test:latest #970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/login:latest # Use ECR
        ports:
        - containerPort: 8080  # Check container's exposed port 
      imagePullSecrets:
      - name: ghcr-credentials
