apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service-deployment
  namespace: login-local-namespace #loginpage-namespace
  labels:
    app: local #fargate
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: local
  template:
    metadata:
     labels:
      app: local
    spec:
      containers:
      - name: loginpage-service
        image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/login:latest #login-page-local-1:latest #ghcr.io/brynnpark/login-test:latest # Use ECR
        ports:
        - containerPort: 8000  # Check container's exposed port 
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        imagePullPolicy: IfNotPresent
      # imagePullSecrets:
      # - name: ecr-secret
      # imagePullSecrets:
      # - name: ghcr-credentials
