apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: login
spec:
  selector:
    svc: login
  ports:
    - protocol: TCP
      name: http
      port: 80            # LoadBalancer listens on port 8080 for loginpage
      containerPort: 8080   # Container port
  type: ClusterIP