apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: login-container
        image: ghcr.io/brynnpark/login-test:latest # Replace with your Docker image
        ports:
        - containerPort: 8000
        #envFrom:
        #- secretRef:
        #    name: login-service-secret  # If you’re using environment variables like .env
